name: apple-health-exporter
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- ca-certificates
- certifi
- feather-format
- icu
- libiconv
- libxml2
- libxslt
- lxml
- m2-ncurses # ncurses was not found
- openssl
- pandas
- pip
- python=3.6.0
- python-dateutil
- pytz
- pyreadline  # readline was not found
- setuptools
- six
- sqlite
- tk
- wheel
- xz
- zlib
- mkl
- numpy
